# Generated by Django 3.2 on 2022-03-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_point', models.DateTimeField(verbose_name='Метка времени')),
                ('user_id', models.IntegerField(verbose_name='id абонента')),
                ('type_event', models.CharField(choices=[('coll', 'Звонок'), ('sms', 'смс'), ('internet', 'Трафик')], max_length=10, verbose_name='Тип услуги')),
                ('size_sale', models.IntegerField(verbose_name='Объем затраченных единиц')),
            ],
        ),
        migrations.CreateModel(
            name='Tariffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('start_data', models.DateField(verbose_name='Дата начала действия')),
                ('end_data', models.DateField(verbose_name='Дата конца действия')),
                ('minuts', models.IntegerField(verbose_name='Объем минут')),
                ('sms', models.IntegerField(verbose_name='Объем смс')),
                ('mb', models.IntegerField(verbose_name='Объем трафика, мегабайт')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(verbose_name='Текущий баланс')),
                ('add_data', models.DateField(verbose_name='Дата добавления')),
                ('age_user', models.IntegerField(verbose_name='Возраст')),
                ('city_user', models.CharField(max_length=30, verbose_name='Город проживания')),
                ('act_time', models.DateTimeField(verbose_name='Временная метка последней активности')),
                ('tariff', models.IntegerField(verbose_name='Активный тариф')),
            ],
        ),
    ]
