# Generated by Django 3.2 on 2022-03-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megafonTestApp', '0002_auto_20220324_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=1000000, verbose_name='Текущий баланс'),
        ),
    ]
